services:
  sufs-manager:
    build: .
    container_name: sufs_manager_web_app
    restart: always
    env_file:
      - .env
    expose:
      - "8000"
    ports:
      - "8000:8000"
    volumes:
      - ./output:/app/output
